api/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api import views
# from django.contrib import admin

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    
    url(r'^rest/', include('customer.urls')),
    url(r'^cuity_fruity/', include('app.urls')),
    url(r'^wallet/', include('wallet.urls')),
    url(r'^shop/', include('shop.urls')),

    url(r'^dashbooard', views.dashboard),
    url(r'^index/', views.index_page),
    # url(r'^', include('customer.urls')),
]

api/wallet/urls.py
# from django.conf.urls import url, include
# from rest_framework.urlpatterns import format_suffix_patterns
# from wallet import views as v



# urlpatterns = [
#     # url(r'^list/$', v.delivery_list),
#     # url(r'^detail/(?P<pk>[0-9]+)/$', v.delivery_detail),
#     url(r'^$', v.Home, name='home'),

#     url(r'^person/$', v.ViewPerson, name='person_detail'),
#     url(r'^person/add$', v.NewPerson, name='person_add'),
#     url(r'^person/lists/$', v.PeopleList, name='people_list'),
#     url(r'^person/update/$', v.EditPerson, name='person_update'),
#     url(r'^person/delete/$', v.KillPerson, name='person_delete'),


#     url(r'^category/$', v.ViewCategory, name='category_detail'),
#     url(r'^NewCategory$', v.NewCategory, name='category_add'),
#     url(r'^category/lists/$', v.CategoryList, name='category_list'),
#     url(r'^category/update/$', v.EditCategory, name='category_update'),
#     url(r'^category/delete/$', v.DeleteCategory, name='category_delete'),
#     url(r'^category/alternate/$', v.CategoryDetail, name='category_detail_alt'),
# ]

# urlpatterns = format_suffix_patterns(urlpatterns)


from django.conf.urls import patterns, url, include
from wallet.views import *

person_urls = patterns('',
    url(r'^$', ViewPerson.as_view(), name='person_detail'),
    url(r'^update$', EditPerson.as_view(), name='person_update'),
    url(r'^delete$', KillPerson.as_view(), name='person_delete'),
)

category_urls = patterns('',
    url(r'^$', ViewCategory.as_view(), name='category_detail'),
    url(r'^alternate$', CategoryDetail.as_view(), name='category_detail_alt'),
    url(r'^update$', EditCategory.as_view(), name='category_update'),
    url(r'^delete$', DeleteCategory.as_view(), name='category_delete'),
)

urlpatterns = patterns('',
    url(r'^peoples$', PeopleList.as_view(), name='people_list'),
    url(r'^(?P<slug>[\w-]+).person/', include(person_urls)),
    url(r'^newperson$', NewPerson.as_view(), name='person_add'),
    url(r'^categories$', CategoryList.as_view(), name='category_list'),
    url(r'^(?P<slug>[\w-]+).cat/', include(category_urls)),
    url(r'^newcategory$', NewCategory.as_view(), name='category_add'),
)

api/wallet/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.template.defaultfilters import slugify
# from django.contrib.localflavor.us.models import PhoneNumberField



class Category(models.Model):
    title = models.CharField(max_length=80)
    slug = models.SlugField(blank=True)
    
    class Meta:
        verbose_name_plural = 'categories'
    
    def __unicode__(self):
        return u"%s" % self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Category, self).save(*args, **kwargs)
    
    @models.permalink
    def get_absolute_url(self):
        return ('category_detail', [self.slug])
    
    @models.permalink
    def get_update_url(self):
        return ('category_update', [self.slug])
    
    @models.permalink
    def get_delete_url(self):
        return ('category_delete', [self.slug])



class Person(models.Model):
    PROXIMITY_LIST = (
        (0, 'Not sure'),
        ('Friends', (
            (10, 'Best friends forever'),
            (20, 'Close friends'),
            (30, 'Distant friends'),
            (40, 'Enemies til the end')
        )),
        ('Family', (
            (50, 'Super close'),
            (60, 'Only on occasion'),
            (70, 'Only at funerals'),
            (80, 'Family grouch!')
        )),
    )

    first_name = models.CharField(max_length=60, help_text='Their first name')
    last_name = models.CharField(max_length=80, blank=True, help_text='Do you know it?')
    slug = models.SlugField(blank=True)
    category = models.ForeignKey(Category, blank=True, null=True, help_text='File this person where?')
    proximity = models.PositiveSmallIntegerField(choices=PROXIMITY_LIST, help_text='How much of a distance to keep?')
    # home_phone = PhoneNumberField(blank=True)
    # cell_phone = PhoneNumberField(blank=True)
    email = models.EmailField(blank=True, help_text='Do they have an Email address?')
    added_on = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'people'
        ordering = ['last_name']
    
    @property
    def full_name(self):
        return u"%s %s" % (self.first_name, self.last_name) if self.last_name != '' else u"%s" % self.first_name
    
    def __unicode__(self):
        return u"%s, %s" % (self.last_name, self.first_name) if self.last_name != '' else u"%s" % self.first_name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.full_name)
        return super(Person, self).save(*args, **kwargs)
    
    @models.permalink
    def get_absolute_url(self):
        return ('person_detail', [self.slug])
    
    @models.permalink
    def get_update_url(self):
        return ('person_update', [self.slug])
    
    @models.permalink
    def get_delete_url(self):
        return ('person_delete', [self.slug])

api/wallet/forms.py
from django import forms
from wallet.models import Category, Person

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('title',)

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'category', 'proximity', 'email',)

api/wallet/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse

from .models import Category, Person
from .forms import CategoryForm, PersonForm



def Home(request):
    return render(request, 'wallet/index.html')#, tmpl_vars)



class CategoryMixin(object):
    model = Category
    def get_context_data(self, **kwargs):
        kwargs.update({'object_name':'Category'})
        return kwargs





class CategoryFormMixin(CategoryMixin):
    form_class = CategoryForm
    template_name = 'wallet/object_form.html'


class CategoryList(CategoryMixin, ListView):
    template_name = 'wallet/object_list.html'


class CategoryDetail(CategoryMixin, DetailView):
    pass


class NewCategory(CategoryFormMixin, CreateView):
    pass


class EditCategory(CategoryFormMixin, UpdateView):
    pass


class DeleteCategory(CategoryMixin, DeleteView):
    template_name = 'wallet/object_confirm_delete.html'
    def get_success_url(self):
        return reverse('category_list')





class PersonMixin(object):
    model = Person
    def get_context_data(self, **kwargs):
        kwargs.update({'object_name':'Person'})
        return kwargs


class PersonFormMixin(PersonMixin):
    form_class = PersonForm
    template_name = 'wallet/object_form.html'


class PeopleList(PersonMixin, ListView):
    template_name = 'wallet/object_list.html'


class ViewPerson(PersonMixin, DetailView):
    pass


class NewPerson(PersonFormMixin, CreateView):
    pass


class EditPerson(PersonFormMixin, UpdateView):
    pass


class KillPerson(PersonMixin, DeleteView):
    template_name = 'wallet/object_confirm_delete.html'
    def get_success_url(self):
        return reverse('people_list')


class ViewCategory(PersonMixin, ListView):
    template_name = 'wallet/object_list.html'
    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        return super(ViewCategory, self).get_queryset().filter(category=self.category)

api/templates/wallet/base.html
<html>

	<head>
	  <title>{% block title %}Untitled{% endblock %} | Phone Directory</title>
	</head>
	
	<body>
		<h1>Phonebook CRUD example!</h1>
		<a href="{% url 'people_list' %}">Index</a> | <a href="{% url 'category_list' %}">Categories</a> | <a href="{% url 'category_add' %}">Add Category</a> | <a href="{% url 'person_add' %}">Add Person</a>
		<hr/>
		{% block content %}
		The end user should never ever see this!
		{% endblock %}
	</body>
</html>

api/templates/wallet/index.html
index.html

api/templates/wallet/object_alt.html
{% extends 'wallet/base.html' %}

{% block title %}{{object}}{% endblock %}

{% block content %}


<table>

	<thead><tr><th>Person</th><th>Action</th></tr></thead>
	<tbody>
	  {% for object in object.person_set.all %}
	  <tr><td><a href="{{object.get_absolute_url}}">{{object}}</a></td><td><a href="{{object.get_update_url}}">Update</a> | <a href="{{object.get_delete_url}}">Delete</a></td></tr>
	  {% endfor %}
	</tbody>

</table>

{% endblock %}

api/templates/wallet/object_confirm_delete.html
{% extends 'wallet/base.html' %}

{% block title %}{{object_name}} Confirm delete?{% endblock %}

{% block content %}

<h3>Are you sure you want to delete {{object}}?</h3>

<form action="" method="post">{% csrf_token %}
	<input type="submit" value="Yes!"/>
	<input type="button" value="No..." onclick="window.history.go(-1);"/>
</form>

{% endblock %}

api/templates/wallet/object_form.html
{% extends 'wallet/base.html' %}

{% block title %}{{object_name}} Form{% endblock %}

{% block content %}
	<h3>{% if object %}Updating {{object}}{% else %}Add a new {{object_name}}{% endif %}</h3>
	
	<form action="" method="post">{% csrf_token %}
		<table>
			{{form}}
		</table>
		<input type="submit" value="Save {{object_name}}"/>
	</form>
	
{% endblock %}

api/templates/wallet/object_list.html
{% extends 'wallet/base.html' %}

{% block title %}{{object_name}} List{% endblock %}

{% block content %}

<table>

	<thead><tr><th>{{object_name}}</th><th>Action</th></tr></thead>

	<tbody>
		{% for object in object_list %}
		<tr>
		  	<td>
		  		<a href="{{object.get_absolute_url}}">{{object}}</a>
		  	</td>
		  	<td>
		  		<a href="{{object.get_update_url}}">Update</a> | <a href="{{object.get_delete_url}}">Delete</a>
		  	</td>
		</tr>
		{% endfor %}
	</tbody>

</table>
{% endblock %}

api/templates/wallet/person_detail.html
{% extends 'wallet/base.html' %}

{% block title %}{{object}}{% endblock %}

{% block content %}

	<table>

		<tr><th>Full name:</th><td>{{object.full_name}}</td></tr>
		<tr><th>Filed under:</th><td><a href="{{object.category.get_absolute_url}}">{{object.category}}</a></td></tr>
		<tr><th>Proximity:</th><td>{{object.get_proximity_display}}</td></tr>
		{% if object.home_phone %}<tr><th>Home Phone:</th><td>{{object.home_phone}}</td></tr>{% endif %}
		{% if object.cell_phone %}<tr><th>Cell Phone:</th><td>{{object.cell_phone}}</td></tr>{% endif %}
		{% if object.email %}<tr><th>Email:</th><td>{{object.email}}</td></tr>{% endif %}
	
	</table>
	
	<a href="{{object.get_update_url}}">Update</a> | <a href="{{object.get_delete_url}}">Delete</a>
{% endblock %}